/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISAO;

import DAO.ProdutoDAO;
import DTO.ProdutoDTO;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tarci
 */
public class frmPrdotu extends javax.swing.JFrame {

    /**
     * Creates new form frmPrdotu
     */
    public frmPrdotu() {
        initComponents();
        listarValores();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUnidade = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaproduto = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        CarregaCampos = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 160, 48, 35);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Descricao");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 220, 70, 20);

        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescricao);
        txtDescricao.setBounds(120, 210, 250, 30);
        getContentPane().add(txtNome);
        txtNome.setBounds(120, 160, 280, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Unidade");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 260, 60, 20);
        getContentPane().add(txtUnidade);
        txtUnidade.setBounds(120, 260, 260, 30);

        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(20, 300, 100, 27);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("Cadastro de Materiais ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 0, 380, 50);

        tabelaproduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Descricao", "Unidade"
            }
        ));
        jScrollPane1.setViewportView(tabelaproduto);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 340, 470, 120);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Codigo");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 120, 60, 20);

        txtCodigo.setEnabled(false);
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(120, 112, 100, 30);

        CarregaCampos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CarregaCampos.setText("Carregar Campos");
        CarregaCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarregaCamposActionPerformed(evt);
            }
        });
        getContentPane().add(CarregaCampos);
        CarregaCampos.setBounds(360, 473, 137, 30);

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(130, 300, 90, 27);

        setSize(new java.awt.Dimension(506, 542));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
     cadastrarProduto();
     listarValores();
     LimparCampos();
    
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void CarregaCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarregaCamposActionPerformed
        // TODO add your handling code here:
        CarregaCampos();
        
    }//GEN-LAST:event_CarregaCamposActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        LimparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrdotu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrdotu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrdotu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrdotu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrdotu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CarregaCampos;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaproduto;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtUnidade;
    // End of variables declaration//GEN-END:variables

private void listarValores(){
    try {
        ProdutoDAO objprodutoDAO = new ProdutoDAO();
        
        DefaultTableModel model = (DefaultTableModel) tabelaproduto.getModel();
        model.setNumRows(0);
        
        ArrayList<ProdutoDTO>lista = objprodutoDAO.PesquisarProduto();
        
        for(int num = 0; num <lista.size(); num++){
            model.addRow(new Object[]{
                lista.get(num).getId_material(),
                lista.get(num).getNome_material(),
                lista.get(num).getDescricao_material(),
                lista.get(num).getQuantidade_material()
                
                
            });
        }
        
    } catch (Exception erro) {
        
        JOptionPane.showMessageDialog(null,"Lista valores " + erro);
    }
}

private void CarregaCampos(){
    int setar = tabelaproduto.getSelectedRow();
    
    txtCodigo.setText(tabelaproduto.getModel().getValueAt(setar, 0).toString());
    txtNome.setText(tabelaproduto.getModel().getValueAt(setar, 1).toString());
    txtDescricao.setText(tabelaproduto.getModel().getValueAt(setar, 2).toString());
    txtUnidade.setText((tabelaproduto).getModel().getValueAt(setar,3).toString());
            
}

private void cadastrarProduto(){
        String nome, descricao;
        int unidade;
        nome= txtNome.getText();
        descricao = txtDescricao.getText();
        unidade = Integer.parseInt(txtUnidade.getText());
        ProdutoDTO objprodutodto = new ProdutoDTO();
        objprodutodto.setNome_material(nome);
        objprodutodto.setDescricao_material(descricao);
        objprodutodto.setQuantidade_material(unidade);
        ProdutoDAO objprodutodao = new ProdutoDAO();
        
        objprodutodao.cadastrarProduto(objprodutodto);
        
}

  private void LimparCampos(){
      txtCodigo.setText("");
      txtNome.setText("");
      txtDescricao.setText("");
      txtUnidade.setText("");
      txtNome.requestFocus();
  }
}
